services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: bingo-driven-backend
    container_name: bingo-driven-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env.test

    depends_on:
      postgres:
        condition: service_healthy

